config/routes.rb
Rails.application.routes.draw do

resources :users

resources :posts

resources :comments

root 'users#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploaders :images, ImagesUploader
  has_many :comments
  belongs_to :user

  def remove_image
    # binding.pry
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  has_many :comments
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end

  def show

    @comment = Comment.find(params[:id])

  end

  def new
    @comments = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to post_path(@comment.post_id)
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(@comment.post_id)
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to users_path
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new

    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to user_path(@post.user_id)
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to users_path
  end

  private

  def post_params
    params.require(:post).permit(:body, :user_id, {images:[]})
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save

      redirect_to users_path
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end


  private
      def user_params
        params.require(:user).permit(:name, :avatar)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1>Edit comment</h1>
<%= form_for @comment do |f| %>
  <%= f.label :body %>:
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<% if @comments.any? %>

  <% @comments.each do |comment| %>
    <ul>
      <li><%= comment.body %></li>

      <hr />
    </ul>
  <% end %>
<% else %>
<h3> No posts found </h3>
<% end %>
<p><%= link_to 'New Comment', new_comment_path %></p>

<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>New Comments</h1>

<%= form_for @comments do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.hidden_field :post_id, value: params[:post_id].to_i %>
  <%= f.submit %>
<% end %>


<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>




<%= link_to 'Back', posts_path %>


<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<p>My Post World</P>
<p>
| <%= link_to 'Home',root_path %> |

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyPostworld</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= render 'layouts/navbar' %>
</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= form_for @post, html: { multipart: true } do |f| %>
  <%= f.label :body %>:
  <%= f.text_field :body %>
  <div class='center'>
    <%= f.file_field :images, multiple: true %>
  </div>
  <% if @post.images.any? %>
    <% @post.images.each do |i| %>
      <%= image_tag i.url(:thumb) %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %>
      <hr />
    <% end %>
    <hr />
  <% elsif %>
    <h4> please add a picture </h4>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>Your Post</h1>


<% if @posts.any? %>

  <% @posts.each do |post| %>


    <ul>
      <li><%= post.body %></li>
      <li><%= post.body %></li>
      <hr />
      <br />
      <li><%= image_tag @post.images[1].url %></li>
      <%= image_tag user.avatar.url(:thumb) %>
      <!-- <% @post.images.each do |image| %>
        <%= image_tag(image.url) %> -->
      <hr />
    </ul>
  <% end %>
<% else %>
<h3> No posts found </h3>
<% end %>
<p><%= link_to 'New Post', new_post_path %></p>


<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.label :images %>
  <%= f.file_field :images, multiple: true %>
  <%= f.hidden_field :user_id, value: params[:user_id].to_i %>
  <%= f.submit %>
<% end %>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<%= link_to 'Back', users_path %>
<h3 class='red'><%= @post.body %></h3>
<!-- <% @post.images.each do |i| %>
  <%= image_tag i %>
<% end %> -->
<hr />
<% if @post.images.any? %>
  <% @post.images.each do |i| %>
    <%= image_tag i.url(:thumb).to_s %>
  <% end %>
<% end %>
<% if @comments.any? %>
  <% @comments.each do |comment| %>
    <ul>
      <h4 class='green'><%= comment.body %></h4>

      <%= link_to 'Edit comment', edit_comment_path(comment) %>
      <%= link_to 'Destroy comment', comment_path(comment), method: :delete %>
    </ul>
  <% end %>
<% else %>
<h3 class='green'> No comments found </h3>
<% end %>
<p class='black-text'><%= link_to 'New comment', new_comment_path(post_id: @post.id) %></p>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %> Profile </h1>
<%= form_for @user do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>

  <%= f.file_field :avatar %>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1 class='center blue orange-text'>PostWorld Users:</h1>
<% if @users.any? %>
  <% @users.each do |user| %>
    <ul>
      <h3 class='brown darken-1 pink-text text-lighten-2'><%= user.name %></h3>
      <%= image_tag user.avatar.url(:thumb) %>

      <%= link_to 'Show User Posts', user_path(user) %> |
      <%= link_to 'Edit User', edit_user_path(user) %> |
      <%= link_to 'Destroy user', user_path(user), method: :delete %>
    </ul>
  <% end %>
<% else %>
<h3> No users found </h3>
<% end %>
<p><%= link_to 'New User', new_user_path %></p>

app/views/users/new.html.erb
<h1>New user</h1>

<hr />
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Posts</h1>
<%= image_tag @user.avatar.url(:thumb) %>
<% if @posts.any? %>

  <% @posts.each do |post| %>
    <ul>
      <h3 class='red'><%= post.body %></h3>
      <% if post.images.any? %>
        <!-- <%= image_tag post.images[1].url(:thumb).to_s %> -->
        <% if post.images.any? %>
          <% post.images.each do |i| %>
            <%= image_tag i.url(:thumb).to_s %>
          <% end %>
        <% end %>
      <% elsif %>
        <h4> no images </h4>
      <% end %>


      <%= link_to "Show post's comments", post_path(post) %> |
      <%= link_to 'Edit post', edit_post_path(post) %> |
      <%= link_to 'Destroy post', post_path(post), method: :delete %>
    </ul>
  <% end %>
<% else %>
<h3> No posts found </h3>
<% end %>
<p><%= link_to 'New Post', new_post_path(user_id: @user.id) %></p>